apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    test: test
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
      nodePort: 30001
  selector:
    demo: k8s-handson
    role: presetdemo
