apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8000
      protocol: TCP
      nodePort: 30002
  selector:
    app: webapp
